apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
  labels:
    app: calc
spec:
  replicas: 13
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
        - name: calc
          image: registry.digitalocean.com/pawel-szafran/calc:CALC_VERSION
          ports:
            - containerPort: 4000
              protocol: TCP
